Blog_Site/Blog_Site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Blog_Site/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path("", views.home_view, name="home"),
    path("about/", views.about_view, name="about"),
    path("post/<int:pk>/", views.show_post_view, name="show_post"),
    path("edit_post/<int:pk>/", views.edit_post_view, name="edit_post"),
    path("create_post/", views.create_post_view, name="create_post"),
    path("delete_post/<int:pk>/", views.delete_post_view, name='delete_post'),
    path("profile/<int:pk>/", views.profile_view, name="profile"),
    path("edit_profile/",views.edit_profile_view, name="edit_profile"),
    path("login/",views.loginPage_view, name="login"),
    path("register/",views.registerPage_view, name="register"),
    path("logout/",views.logout_view, name="logout"),

]

Blog_Site/templates/footer.html
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
            <ul class="list-inline text-center">
                <li class="list-inline-item">
                    <a href="https://twitter.com/Zanda0690">
                        <span class="fa-stack fa-lg">
                            <i class="fas fa-circle fa-stack-2x"></i>
                            <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                        </span>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="https://www.instagram.com/nicozero34/">
                        <span class="fa-stack fa-lg">
                            <i class="fas fa-circle fa-stack-2x"></i>
                            <i class="fab fa-instagram fa-stack-1x fa-inverse"></i>
                        </span>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="https://github.com/nico-Zero">
                        <span class="fa-stack fa-lg">
                            <i class="fas fa-circle fa-stack-2x"></i>
                            <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                        </span>
                    </a>
                </li>
            </ul>
            <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
        </div>
    </div>
</div>

Blog_Site/templates/index.html
{% load bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta
			name="viewport"
			content="width=device-width, initial-scale=1, shrink-to-fit=no"
		/>
		<meta name="description" content="" />
		<meta name="author" content="" />
		<title>Nico's Blog</title>
		{% block styles %} {% bootstrap_css %} {% bootstrap_javascript %} 
		<link
			rel="icon"
			type="image/x-icon"
			href="{% static 'assets/favicon.ico' %}"
		/>
		<!-- Font Awesome icons (free version)-->
		<script
			src="https://use.fontawesome.com/releases/v6.3.0/js/all.js"
			crossorigin="anonymous"
		></script>
		<!-- Google fonts-->
		<link
			href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic"
			rel="stylesheet"
			type="text/css"
		/>
		<link
			href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
			rel="stylesheet"
			type="text/css"
		/>

		<!-- Core theme CSS (includes Bootstrap)-->
		<link
			href="{% static 'css/styles.css' %}"
			rel="stylesheet"
		/>
        {% endblock %}
	</head>
    <header class="masthead" style="background-image: url({% block header-image %}{% endblock header-image %})">
        <!-- Navigation-->
        {% include "navbar.html" %}
		
		<!-- Page Header-->
		{% block header %}
		{% endblock header %}
    </header>
	<body>
        
        <!-- Main Content-->
        {% block content %}
        {% endblock content %}
        
	</body>
    <footer class="border-top footer">
        <!--Footer-->
        {% include "footer.html" %}
        
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}" type="text/javascript"></script>
    </footer>
</html>

Blog_Site/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
	<div class="container px-4 px-lg-5">
		<a class="navbar-brand" href="/">Blogger Heaven</a>
		<button
			class="navbar-toggler"
			type="button"
			data-bs-toggle="collapse"
			data-bs-target="#navbarResponsive"
			aria-controls="navbarResponsive"
			aria-expanded="false"
			aria-label="Toggle navigation"
		>
			Menu
			<i class="fas fa-bars"></i>
		</button>
		<div class="collapse navbar-collapse" id="navbarResponsive">
			<ul class="navbar-nav ms-auto py-4 py-lg-0">
				<li class="nav-item active">
					<a
						class="nav-link px-lg-3 py-3 py-lg-4"
						href="{% url "main:home" %}"
						>Home</a
					>
				</li>
                {% if not user.is_authenticated %}
				<li class="nav-item">
					<a
						class="nav-link px-lg-3 py-3 py-lg-4"
						href="{% url 'main:about' %}"
						>About</a
					>
				</li>
				<li class="nav-item">
					<a
						class="nav-link px-lg-3 py-3 py-lg-4"
						href="{% url "main:login" %}"
						>Login</a
					>
				</li>
				<li class="nav-item">
					<a
						class="nav-link px-lg-3 py-3 py-lg-4"
						href="{% url "main:register" %}"
						>Register</a
					>
				</li>
				{% else %}
				<li class="nav-item">
					<a
						class="nav-link px-lg-3 py-3 py-lg-4"
						href="{% url 'main:profile' user.pk %}"
						>Profile</a
					>
				</li>
				<li class="nav-item">
					<a
						class="nav-link px-lg-3 py-3 py-lg-4"
						href="{% url 'main:about' %}"
						>About</a
					>
				</li>
				<li class="nav-item">
					<a
						class="nav-link px-lg-3 py-3 py-lg-4"
						href="{% url "main:logout" %}"
						>Log Out</a
					>
				</li>
				{% endif %}
			</ul>
		</div>
	</div>
</nav>