Blog_Site/Blog_Site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Blog_Site/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path("", views.home_view, name="home"),
    path("about/", views.about_view, name="about"),
    path("post/<int:pk>/", views.show_post_view, name="show_post"),
    path("edit_post/<int:pk>/", views.edit_post_view, name="edit_post"),
    path("create_post/", views.create_post_view, name="create_post"),
    path("delete_post/<int:pk>/", views.delete_post_view, name='delete_post'),
    path("profile/<int:pk>/", views.profile_view, name="profile"),
    path("edit_profile/",views.edit_profile_view, name="edit_profile"),
    path("login/",views.loginPage_view, name="login"),
    path("register/",views.registerPage_view, name="register"),
    path("logout/",views.logout_view, name="logout"),

]

Blog_Site/main/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    about = RichTextField(default="No About...")
    avatar = models.ImageField(upload_to="avatars", default="no_picture.png")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username.capitalize()

    def like(self, post):
        if not self.is_liked(post=post):
            if self.is_disliked(post=post):
                self.un_dislike(post=post)
            like = Likes(user=self.user, post=post)
            like.save()
        else:
            self.un_like(post=post)

    def is_liked(self, post):
        try:
            self.user.likes.get(post=post)  # type: ignore
            return True
        except Exception as e:
            return False

    def un_like(self, post):
        un_like = Likes.objects.get(user=self.user, post=post)
        un_like.delete()

    def dislike(self, post):
        if not self.is_disliked(post=post):
            if self.is_liked(post=post):
                self.un_like(post=post)
            dislike = Dislikes(user=self.user, post=post)
            dislike.save()
        else:
            self.un_dislike(post=post)

    def is_disliked(self, post):
        try:
            self.user.dislikes.get(post=post)  # type: ignore
            return True
        except:
            return False

    def un_dislike(self, post):
        un_dislike = Dislikes.objects.get(user=self.user, post=post)
        un_dislike.delete()


class Post(models.Model):
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="posts")
    title = models.CharField(max_length=1000, blank=False)
    subtitle = models.CharField(max_length=1000, blank=True)
    body = RichTextField(default="No Body...")
    header_image_url = models.URLField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title.capitalize()

    def get_like_count(self):
        likes = self.likes.all()  # type: ignore
        print(likes)


class Likes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="likes")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="likes")

    def __str__(self):
        return self.user.username + " - " + self.post.title


class Dislikes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="dislikes")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="dislikes")

    def __str__(self):
        return self.user.username + " - " + self.post.title


class Comment(models.Model):
    comment = RichTextField(default="No Comment...")
    author = models.ForeignKey(
        Profile, on_delete=models.CASCADE, related_name="comments"
    )
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return (
            "Author:- "
            + self.author.user.username.capitalize()
            + ", Blog:- "
            + self.post.title
        )

Blog_Site/main/forms.py
from .models import Post, Comment, Profile
from django import forms
from ckeditor.fields import RichTextField
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SearchForm(forms.Form):
    search = forms.CharField(max_length=120, required=False)

class LoginForm(forms.Form):
    username = forms.CharField(max_length=120)
    password = forms.CharField(max_length=16, widget=forms.PasswordInput)

class RegisterForm(UserCreationForm):
    class Meta:
        model=User
        fields = ('username','email' ,'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["about"]

    def __init__(self, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)

    def save(self, commit=True, *args, **kwargs):
        instance = super(EditProfileForm, self).save(commit=False, *args, **kwargs)
        return instance.save() if commit else instance

class ContactForm(forms.Form):
    name = forms.CharField(max_length=120, required=False)
    message = RichTextField(default="Just Want to Talk...")

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "subtitle", "body", "header_image_url"]

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)

    def save(self, commit=True, *args, **kwargs):
        instance = super(PostForm, self).save(commit=False, *args, **kwargs)
        return instance.save() if commit else instance


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["comment"]

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)

    def save(self, commit=True, *args, **kwargs):
        instance = super(CommentForm, self).save(commit=False, *args, **kwargs)
        return instance.save() if commit else instance

Blog_Site/main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .models import Profile, Post
from .forms import (
    CommentForm,
    PostForm,
    EditProfileForm,
    LoginForm,
    RegisterForm,
    SearchForm,
)
from django.http import HttpResponseRedirect

# Create your views here.


def loginPage_view(request):
    if request.user.is_authenticated:
        return redirect("main:home")

    if request.method == "POST":
        username = request.POST.get("username").lower()
        password = request.POST.get("password")
        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, "User does not exist.")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("main:home")
        else:
            messages.error(request, "Username or password is incorrect.")
    login_form = LoginForm()

    context = {"login_form": login_form}

    return render(request, "main/login.html", context=context)


@login_required(login_url="main:login")
def logout_view(request):
    logout(request)
    return redirect("main:login")


def registerPage_view(request):
    form = RegisterForm()

    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            profile = Profile(user=user)
            profile.save()
            login(request, user)
            return redirect("main:home")
        else:
            messages.error(request, "An error occurred while registration.")

    context = {"form": form}
    return render(request, "main/register.html", context=context)


@login_required(login_url="main:login")
def home_view(request):
    if not request.user.is_authenticated:
        return redirect("main:login")
    search_form = SearchForm()
    user_profile = Profile.objects.get(user=request.user)
    
    posts = Post.objects.all()
    if request.method == "POST":
        like_post_pk = request.POST.get("like")
        dislike_post_pk = request.POST.get("dislike")
        search_form = SearchForm(request.POST)
        if like_post_pk:
            post = Post.objects.get(pk=like_post_pk)
            user_profile.like(post)
        elif dislike_post_pk:
            post = Post.objects.get(pk=dislike_post_pk)
            user_profile.dislike(post)
        elif search_form.is_valid():
            search = dict(search_form.data.items())["search"]
            posts = Post.objects.filter(title__contains=search)
            search_form = SearchForm()

    liked_post_list = [i.post for i in request.user.likes.all()]
    disliked_post_list = [i.post for i in request.user.dislikes.all()]
    
    
    context = {
        "posts": posts,
        "search_form": search_form,
        "liked_post_list": liked_post_list,
        "disliked_post_list": disliked_post_list,
    }
    return render(request, "main/home.html", context=context)


def about_view(request):
    return render(request, "main/about.html")


@login_required(login_url="main:login")
def show_post_view(request, pk):
    post = Post.objects.get(pk=pk)
    comments = post.comments.all()  # type: ignore

    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.author = Profile.objects.get(user=request.user)
            comment.post = post
            comment.save()
            return HttpResponseRedirect(f"/post/{pk}/")
    else:
        comment_form = CommentForm()

    context = {
        "post": post,
        "comments": comments,
        "comment_form": comment_form,
    }

    return render(request, "main/post.html", context=context)


@login_required(login_url="main:login")
def edit_post_view(request, pk):
    post = Post.objects.get(pk=pk)
    edit_post_form = PostForm(instance=post)

    if request.method == "POST":
        edit_post_form = PostForm(request.POST)
        if edit_post_form.is_valid():
            new_post = edit_post_form.save(commit=False)

            post.title = new_post.title
            post.subtitle = new_post.subtitle
            post.body = new_post.body
            post.header_image_url = new_post.header_image_url
            post.save()
            return redirect("main:home")

    context = {"edit_post_form": edit_post_form}
    return render(request, "main/edit_post.html", context=context)


@login_required(login_url="main:login")
def create_post_view(request):
    if request.method == "POST":
        create_post_form = PostForm(request.POST)
        if create_post_form.is_valid():
            new_post = create_post_form.save(commit=False)
            profile = Profile.objects.get(user=request.user)
            new_post.author = profile
            new_post.save()

            return redirect("main:home")
    else:
        create_post_form = PostForm()

    context = {"create_post_form": create_post_form}
    return render(request, "main/create_post.html", context=context)


@login_required(login_url="main:login")
def delete_post_view(request, pk):
    post = Post.objects.get(pk=pk)
    post.delete()

    return redirect("main:home")


@login_required(login_url="main:login")
def profile_view(request, pk):
    profile = Profile.objects.get(user=User.objects.get(pk=pk))
    context = {"profile": profile}
    return render(request, "main/profile.html", context=context)


@login_required(login_url="main:login")
def edit_profile_view(request):
    profile = Profile.objects.get(user=request.user)
    edit_profile_form = EditProfileForm(instance=profile)
    if request.method == "POST":
        edit_profile_form = EditProfileForm(request.POST)
        if edit_profile_form.is_valid():
            new_profile = edit_profile_form.save(commit=False)
            profile.about = new_profile.about
            profile.save()
            return redirect("main:profile", profile.pk)

    context = {
        "profile": profile,
        "edit_profile_form": edit_profile_form,
    }

    return render(
        request,
        "main/edit_profile.html",
        context=context,
    )

Blog_Site/main/templates/main/about.html
{% extends "index.html" %}
<!--Page Header Image -->
{% block header-image %}'../static/assets/img/about-bg.jpg'{% endblock header-image %}

<!--Page Header-->
{% block header %}
<div class="container position-relative px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      <div class="page-heading">
        <h1>About Me</h1>
        <span class="subheading">This is what I do.</span>
      </div>
    </div>
  </div>
</div>
{% endblock header %}

<!--Main Content-->
{% block content %}
<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
          <p>
            My blog site serves as a dynamic platform for an eclectic community of writers and readers alike. Embracing a diverse range of voices and perspectives, the site fosters a vibrant environment where numerous individuals share their unique insights, experiences, and thoughts through blog posts. Whether it's personal narratives, informative articles, creative pieces, or thought-provoking discussions, contributors engage with a wide array of topics, reflecting the rich tapestry of human interests and passions.
          </p>
          <p>
            The platform operates as a virtual forum where users can not only publish their own blogs but also explore a treasure trove of content contributed by others. Through an intuitive interface and user-friendly design, individuals can easily navigate and discover a plethora of engaging articles across various categories. This interactive space encourages meaningful interactions, discussions, and exchanges among the blogging community, fostering connections and collaborations among like-minded individuals or those with contrasting viewpoints.
          </p>
          <p>
            By providing an open space for expression and dialogue, my blog site serves as a melting pot of ideas, enabling readers to broaden their perspectives, gain new insights, and connect with diverse narratives from contributors worldwide. As a hub for creativity and knowledge-sharing, this platform celebrates the power of storytelling and enables individuals to both contribute their own narratives and explore the rich tapestry of experiences and ideas presented by others.
          </p>
      </div>
    </div>
  </div>
</main>
{% endblock content %}

Blog_Site/main/templates/main/create_post.html
{% extends "index.html" %} 
{% block header-image %}'../static/assets/img/edit-bg.jpg'{% endblock header-image %}

<!-- Page Header -->
{% block header %}
<div class="container position-relative px-4 px-lg-5">
	<div class="row gx-4 gx-lg-5 justify-content-center">
		<div class="col-md-10 col-lg-8 col-xl-7">
			<div class="page-heading">
				<h1>New Blog</h1>
				<span class="subheading"
					>You can create a great blog post.</span
				>
			</div>
		</div>
	</div>
</div>
{% endblock header %}

<!--Main Content-->
{% block content %}
<main class="mb-4">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 col-md-10 mx-auto">
				<form method='POST'>
					{% csrf_token %}
					{{create_post_form.media}}
					{{create_post_form.as_p}}
					<input type="submit">
				</form>
			</div>
		</div>
	</div>
</main>
{% endblock content %}

Blog_Site/main/templates/main/edit_post.html
{% extends "index.html" %}

{% block header-image %}'../../static/assets/img/edit-bg.jpg'{% endblock header-image %}

<!-- Page Header -->
{% block header %}
<div class="container position-relative px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      <div class="page-heading">
        <h1>Edit Blog</h1>
        <span class="subheading"
          >You are going to edit your blog post.</span
        >
      </div>
    </div>
  </div>
</div>
{% endblock header %}

<!--Main Content-->
{% block content %}
<main class="mb-4">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <form method="POST">
          {% csrf_token %}
          {{edit_post_form.media}}
          {{edit_post_form.as_p}}
          <input type="submit">
        </form>
      </div>
    </div>
  </div>
</main>
{% endblock content %}



Blog_Site/main/templates/main/edit_profile.html
{% extends "index.html" %}

<!--Page Header Image -->
{% block header-image %}'../static/assets/img/editing-profile-bg.png'{% endblock header-image %}

<!--Page Header-->
{% block header %}
<div class="container position-relative px-4 px-lg-5">
	<div class="row gx-4 gx-lg-5 justify-content-center">
		<div class="col-md-10 col-lg-8 col-xl-7">
			<div class="page-heading">
				<h1>Editing {{profile.user.username | capfirst}}'s</h1>
			</div>
		</div>
	</div>
</div>
{% endblock header %}

<!--Main Content-->
{% block content %}
<main class="mb-4">
	<div class="container px-4 px-lg-5">
		<div class="row gx-4 gx-lg-5 justify-content-center">
			<div class="col-md-10 col-lg-8 col-xl-7">
                <form method="POST">
                    {% csrf_token %}
                    {{edit_profile_form.media}}
                    {{edit_profile_form.as_p}}
                    <input type="submit">
                </form>
            </div>
		</div>
	</div>
</main>
{% endblock content %}

Blog_Site/main/templates/main/home.html
{% extends "index.html" %} 
{% load static %}

{% block header-image %} '../static/assets/img/home-bg.jpg' {% endblock header-image %}

{% block header %}
	<div class="container position-relative px-4 px-lg-5">
		<div class="row gx-4 gx-lg-5 justify-content-center">
			<div class="col-md-10 col-lg-8 col-xl-7">
				<div class="site-heading">
					<h1>{{user.username | capfirst}}'s Blog</h1>
					<span class="subheading"
						>Behold! Here lies the collection of my blogs!</span
					>
				</div>
			</div>
		</div>
	</div>
{% endblock header %} 

{% block content %}
<div class="container px-4 px-lg-5">
	<div class="d-flex justify-content-end">
		<form method="POST">
			{% csrf_token %}
			{{search_form.media}}
			{{search_form.as_p}}
			<input type="hidden">
		</form>
	</div>
	<div class="row gx-4 gx-lg-5 justify-content-center">
		<div class="col-md-10 col-lg-8 col-xl-7">
			<!-- Blog preview-->
			{% if posts %}
			{% for post in posts %}

			<div class="container">
				<div class="row">
					<div class="col-md-10">
						<div class="row">
							<div class="col-md-12">
								<div class="post-preview">
									<a href="{% url 'main:show_post' pk=post.id %}">
										<h2 class="post-title">{{ post.title | capfirst}}</h2>
										<h3 class="post-subtitle">{{ post.subtitle }}</h3>
									</a>
									<p class="post-meta">
										Posted by
										<!-- post.author.name is now a User object -->
										<a href="{% url 'main:profile' post.author.user.pk %}">{{post.author.user.username}}</a>
										on {{post.created}}
										<!-- Only show delete button if user id is 1 (admin user) -->
										{% if post.author.user == user %}
										<a href="{% url 'main:delete_post' post.pk %}">✘</a>
										{% endif %}
									</p>
								</div>
								<!-- Divider-->
								<hr class="my-4" />
							</div>
						</div>
					</div>
				    <div class="col-md-1">
					    <div class="row">
					        <div class="col-md-12 ">
								<form method="POST">
									{% csrf_token %}
									<input type="hidden" name="like" value="{{post.pk}}">
									{% if post in liked_post_list %}
									<input type="image" src="{% static "/assets/like_dislike_24/png/red_like.png" %}" alt="Submit">
									{% else %}
									<input type="image" src="{% static "/assets/like_dislike_24/png/black_like.png" %}" alt="Submit">
									{% endif %}
								</form>
							</div>
						</div>
						<div class="row">
							<div class="col-md-12 ">
								<form method="POST">
									{% csrf_token %}
									<input type="hidden" name="dislike" value="{{post.pk}}">
									{% if post in disliked_post_list  %}
									<input type="image" src="{% static "/assets/like_dislike_24/png/blue_dislike.png" %}" alt="Submit">
									{% else %}
									<input type="image" src="{% static "/assets/like_dislike_24/png/black_dislike.png" %}" alt="Submit">
									{% endif %}
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
			{% endfor %}
			{% else %}
			<div class="post-preview">
				<h2>No Blogs...</h2>
			</div>
			{% endif %}
			<!-- New Blog -->
			<div class="d-flex justify-content-end mb-4">
				<a
					class="btn btn-primary float-right"
					href="{% url 'main:create_post' %}"
					>Create New Blog</a
				>
			</div>
		</div>
	</div>
</div>
{% endblock content %}

Blog_Site/main/templates/main/login.html
{% extends "index.html" %} {% block header-image %}'../static/assets/img/login-bg.jpg'{% endblock header-image %}

<!-- Page Header -->
{% block header %}
<div class="container position-relative px-4 px-lg-5">
	<div class="row gx-4 gx-lg-5 justify-content-center">
		<div class="col-md-10 col-lg-8 col-xl-7">
			<div class="page-heading">
				<h1>Log In</h1>
				<span class="subheading">Welcome to Blogger</span>
			</div>
		</div>
	</div>
</div>
{% endblock header %}

<!--Main Content-->
{% block content %}
<main class="mb-4">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 col-md-10 mx-auto">
				<div>
					<form action="" method="POST">
						{% csrf_token %}
						{{login_form.as_p}}
						<input type="submit" value="Login" />
					</form>
	
					<p>Haven't signed up yet</p>
	
					<div class="d-flex justify-content-end mb-4">
						<a
							class="btn btn-primary float-right"
							href="{% url 'main:register' %}"
							>Signup</a
						>
					</div>
				</div>
			</div>
		</div>
	</div>
</main>

{% endblock content %}

Blog_Site/main/templates/main/post.html
{% extends "index.html" %}

{% block header-image %}{{post.header_image_url}}{% endblock header-image %}

<!-- Page Header-->
{% block header %}
<div class="container position-relative px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      <div class="post-heading">
        <h1>{{ post.title | capfirst}}</h1>
        <h2 class="subheading">{{ post.subtitle }}</h2>
        <span class="meta"
          >Posted by
          <!-- Changed from post.author -->
          <a href="#">{{ post.author.user.username }}</a>
          on {{ post.created}}
        </span>
      </div>
    </div>
  </div>
</div>
{% endblock header %}

<!--Main Content-->
{% block content %}
<article>
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        {{ post.body|safe }}
        <!--Only show Edit Blog button if user id is 1 (admin user) -->
        {% if post.author.user.id == user.id %}
        <div class="d-flex justify-content-end mb-4">
          <a
            class="btn btn-primary float-right"
            href="{% url 'main:edit_post' post.pk %}"
            >Edit Blog</a
          >
        </div>
        {% endif %}

        <!-- Comments Area -->
        <form method='POST'>
          {% csrf_token %}
          {{ comment_form.media }}
          {{ comment_form.as_p }}
          <input type="submit"/>
        </form>
        
        <div class="comment">
          <ul class="commentList">
            <!-- Show all comments -->
            {% for comment in comments %}
              <li>
                <div class="commenterImage">
                  <img
                    src='../../../media/{{comment.author.avatar}}'
                  />
                </div>
                <div class="commentText">
                  <a class="sub-text" href={% url 'main:profile' comment.author.user.pk %}>{{comment.author.user.username | capfirst}}</a>
                  {{comment.comment |safe}}
                </div>
              </li>
            {% endfor %}
          </ul>
        </div> 
      </div>
    </div>
  </div>
</article> 
{% endblock content %}

Blog_Site/main/templates/main/profile.html
{% extends "index.html" %}

<!--Page Header Image -->
{% block header-image %} '../../media/{{profile.avatar}}'{% endblock header-image %}

<!--Page Header-->
{% block header %}
<div class="container position-relative px-4 px-lg-5">
	<div class="row gx-4 gx-lg-5 justify-content-center">
		<div class="col-md-10 col-lg-8 col-xl-7">
			<div class="page-heading">
				<h1>{{profile.user.username | capfirst}}</h1>
				<span class="subheading">This is what I do.</span>
			</div>
		</div>
	</div>
</div>
{% endblock header %}

<!--Main Content-->
{% block content %}
<main class="mb-4">
	<div class="container px-4 px-lg-5">
		<div class="row gx-4 gx-lg-5 justify-content-center">
			<div class="col-md-10 col-lg-8 col-xl-7">
                {{profile.about | safe}}
            </div>
			<div class="d-flex justify-content-end mb-4">
				{% if profile.user.id == user.id %}
				<a
					class="btn btn-primary float-right"
					href="{% url 'main:edit_profile' %}"
					>Edit Profile</a
				>
				{% endif %}
			</div>
		</div>
	</div>
</main>
{% endblock content %}

Blog_Site/main/templates/main/register.html
{% extends "index.html" %}

{% block header-image %}'../static/assets/img/register-bg.jpg'{% endblock header-image %}

<!-- Page Header -->
{% block header %}
<div class="container position-relative px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      <div class="page-heading">
        <h1>Register</h1>
        <span class="subheading">Start Contributing to the Blog!</span>
      </div>
    </div>
  </div>
</div>
{% endblock header %}

<!--Main Content-->
{% block content %}
<main class="mb-4">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div>
          <form action="" method="POST">
              {% csrf_token %}
              {{form.as_p}}
              <input type="submit" value="Register">
          </form>

          <p>Alredy Signed Up</p>
          <a href="{% url "main:login" %}">Login</a>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock content %}